- README.md
1. add demo URL with credentials 
2. add deployment notes
> update README.md to add deployment notes and demo

- oneid/authentication.py
- oneid/settings.py
- oneid/statistics.py
- siteapi/v1/blueprint.md
- siteapi/v1/urls.py
- siteapi/v1/views/config.py
- siteapi/v1/views/statistics.py
- siteapi/v1/views/ucenter.py
> feat: 添加活跃人数，管理员信息等接口

- siteapi/v1/blueprint.md
- siteapi/v1/views/perm.py
> feat: perm owner添加重置所有owner状态的功能

- infrastructure/serializers/email.py
- infrastructure/templates/email/common.html
将产品名称由 OneID 改为 ArkID
范围包括所有面向产品使用者的部分，不涉及代码、文档中命名的修改
> refactor(meta): rename project name from OneID to ArkID

- oauth2_provider/backends.py
- oauth2_provider/views/base.py
/oauth/userinfo/  token 前缀改用 bearer
> refactor(oauth2.0): refactor oauth2.0 userinfo

- siteapi/v1/serializers/config.py
- test/data/test.sql
- test/tests/test_normal_user_view.py
> fix(config):alipay_config_serializer

- oneid_meta/migrations/0070_default_org.py
Signed-off-by: Catomorphism <yangjianing@longguikeji.com>
> fix migration error

- Makefile
- infrastructure/serializers/sms.py
- infrastructure/tests/test_sms.py
- infrastructure/utils/sms.py
- oneid_meta/models/user.py
- siteapi/v1/blueprint.md
- siteapi/v1/tests/test_basic.py
- siteapi/v1/tests/test_config.py
- siteapi/v1/tests/test_ucenter.py
> refactor(mobile): support i18n mobile

- oneid/authentication.py
- oneid/settings.py
- oneid/settings_test.py
- siteapi/v1/tests/test_basic.py
> feat(auth): support sudo Auth

- oneid_meta/models/user.py
- siteapi/v1/blueprint.md
- siteapi/v1/tests/test_perm.py
- siteapi/v1/views/perm.py
> feat(perm): add api to get user_perm result realtime

- devops/jenkinsfile.dev
- devops/jenkinsfile.release
流水线添加发送镜像发送到 DockerHub，longguikeji/arkid:v2dev
> jenkinsfile ci流水线

- extension_root/feishu/user_info_manager.py
> fix: 🐛 修复语法错误

- extension_root/feishu/provider.py
> feat: 🎸 增加了一个绑定用户的方法

- extension_root/aliyun_sms/__init__.py
- extension_root/huawei_sms/__init__.py
- extension_root/huawei_sms/constants.py
- extension_root/huawei_sms/provider.py
- extension_root/huawei_sms/serializers.py
- runtime/__init__.py
> feat: 🎸 支持华为云短信

- extension/utils.py
- extension_root/gitee/provider.py
- extension_root/gitee/views.py
- external_idp/admin.py
> fix: 🐛 gitee绑定错误修复

- extension_root/gitee/serializers.py
- extension_root/gitee/views.py
> fix: 🐛 url参数错误

- extension_root/gitee/views.py
- inventory/models.py
> feat: 🎸 完成gitee绑定

- extension_root/gitee/views.py
> fix: 🐛 去掉url编码

- api/v1/urls/__init__.py
- api/v1/urls/tenant.py
- api/v1/views/tenant.py
支持通过slug获取Tenant
✅ Closes: #193
> feat: 🎸 支持通过slug获取Tenant

- extension_root/feishu/admin.py
- extension_root/feishu/serializers.py
- extension_root/feishu/views.py
> feat: 🎸 完善飞书登录功能和飞书绑定功能

- extension_root/github/provider.py
- extension_root/github/serializers.py
- extension_root/github/views.py
> fix: 🐛 fix github login error

- api/v1/serializers/user.py
- api/v1/urls/__init__.py
- api/v1/urls/user.py
- api/v1/views/user.py
- extension_root/oauth2_authorization_server/serializers.py
> 需要一个验证当前token是否有效的接口

- api/v1/serializers/extension.py
- api/v1/serializers/market_extension.py
- common/extension.py
- extension_root/aliyun_sms/__init__.py
- extension_root/demo/__init__.py
- extension_root/feishu/__init__.py
- extension_root/gitee/__init__.py
- extension_root/github/__init__.py
- extension_root/huawei_sms/__init__.py
- extension_root/inmem_cache/__init__.py
- extension_root/ldap/__init__.py
- extension_root/local_storage/__init__.py
- extension_root/oauth2_authorization_server/__init__.py
- extension_root/oss_storage/__init__.py
- extension_root/otp_mfa/__init__.py
- extension_root/redis_cache/__init__.py
> feat: 🎸 插件支持指定Tag

- requirements-dev.txt
- requirements.txt
> fix: 添加依赖 import-export

- api/v1/serializers/market_extension.py
- api/v1/serializers/user.py
- api/v1/urls/__init__.py
- api/v1/urls/marketplace.py
- api/v1/urls/user.py
- api/v1/views/marketplace.py
- api/v1/views/user.py
- extension_root/arkid/__init__.py
根据用户token返回用户信息
✅ Closes: #314
> feat: 🎸 根据用户token返回用户信息

- extension_root/oauth2_authorization_server/provider.py
> feat: 🎸 保存algorithm

- Pipfile.lock
- requirements-dev.txt
- requirements.txt
依赖添加pillow
- pipfile.lock
由 pipfile 生成 pipfile.lock文件
pipenv install
- requirements.txt
由 pipfile.lock生成 requirements.txt文件
pipenv lock -r > requirements.txt
pipenv lock -r --dev > requirements-dev.txt
> feat: 依赖添加pillow

- Dockerfile
- docker-entrypoint.sh
> feat: 容器启动用户root改为arker

- docker-entrypoint.sh
feat: 容器去掉修改owner为arker，无法修改configmap挂载的配置文件
> feat: 容器去掉修改owner为arker，无法修改configmap挂载的配置文件

- Dockerfile
- docker-entrypoint.sh
> feat: 修改容器启动用户为arkid

- .github/workflows/dev.yml
- .github/workflows/status.yml
> feat: github action cicd

- requirements.txt
> 缺少包pysaml2

- requirements-dev.txt
- requirements.txt
> feat: 添加依赖

- .github/workflows/dev.yml
- .github/workflows/status.yml
流水线增加v2镜像v2dev推送到dockerhub，流水线通知添加分支显示
> feat: 优化流水线

- django_python3_ldap/ldap.py
- django_python3_ldap/management/commands/conf.py
- django_python3_ldap/management/commands/ldap_sync.py
- extension_root/ldap_sync/__init__.py
- extension_root/ldap_sync/provider.py
- extension_root/ldap_sync/serializers.py
- extension_root/ldap_sync/signals.py
- extension_root/ldap_sync/tasks.py
- extension_root/ldap_sync/utils.py
- tests/extension/test_extension_ldap_sync.py
添加 LDAP 同步插件 ldap_sync， 添加 LDAP 同步命令行工具
close #497
> Feature ldap sync

- Pipfile.lock
- requirements-dev.txt
- requirements.txt
容器部署需要 requirements.txt，修复更新 pipfile 后 requirements.txt 未更新
> fix: 🐛 fix pip requirements

- api/v1/views/marketplace.py
- api/v1/views/tenant.py
- tenant/migrations/0028_add_tenant_switch.py
> Feature tenant switch

- api/v1/pages/tenant.py
- api/v1/serializers/tenant.py
- api/v1/views/tenant.py
- api/v1/views/user.py
> Feature tenant switch role

- api/v1/serializers/user.py
- api/v1/views/extension.py
- common/serializer.py
> fix: 🐛 fix empty json data

- api/v1/pages/__init__.py
修改OpenAPI的info中的routers配置信息，将系统管理菜单内容的子菜单统一向上移动一级，去掉系统管理菜单。
> feat: 🎸 update page routers config

- api/v1/views/user.py
- common/extension.py
- extension_root/arkid/__init__.py
- extension_root/gitee/__init__.py
- extension_root/github/__init__.py
- extension_root/huawei_sms/__init__.py
- extension_root/miniprogram/__init__.py
- inventory/models.py
第三方登录插件的用户model导入，需要放在方法里面去导入，否则在插件不启动的情况下，会报错
> 查询用户信息绑定，现在改为了灵活加载，降低了代码之间的互相依赖

- api/v1/pages/group_permission.py
> feat: 🎸 update group_permission page-tag config

- api/v1/pages/__init__.py
- api/v1/pages/arkstore.py
- api/v1/pages/bind_saas.py
- api/v1/serializers/arkstore.py
- api/v1/serializers/bind_saas.py
- api/v1/urls/__init__.py
- api/v1/urls/arkstore.py
- api/v1/urls/bind_saas.py
- api/v1/views/arkstore.py
- api/v1/views/bind_saas.py
- arkid/settings.py
- extension_root/oauth2_authorization_server/provider.py
- oauth2_provider/views/base.py
- 添加本地arkid与中心arkid绑定功能
- 添加插件商店
> Feature arkstore

- api/v1/serializers/log.py
> fix: 🐛 log output timezone

- oauth2_provider/views/base.py
oauth/oidc 权限控制中加入类型 OIDC-Platform 和 arkstore 特殊处理
> fix: 🐛 add type OIDC-Platform to oauth permission

- arkid/core/expand.py
- arkid/core/extension/external_idp.py
- arkid/core/models.py
- arkid/extension/loader.py
> fix: 🐛 修复expand对象save方法

- api/v1/views/arkstore.py
- api/v1/views/bind_saas.py
- arkid.toml
- arkid/common/arkstore.py
- arkid/settings.py
- arkid/urls.py
- oauth2_provider/settings.py
> Feature arkstore local

- .github/workflows/mkdocs.yml
> ci: mkdocs优化
